### ISSUE TITLE
清空问题

### ISSUE THREAD

**Issue by CrazyCoderShi** [zhwayne/WLUnitField#1]
如何清空之前输入的text?
一般都会有会这样的场景,输入一个password, 然后make sure一下
个人觉得可以把text的readonly改成readwrite?

**Comment by CrazyCoderShi** [comment]
刚刚没有仔细读源码
我自己添加了一个clean方法,remove掉所有string的内容,然后重新layout, 就能清空了

**Comment by zhwayne** [comment]
@CrazyCoderShi 多谢你的建议，`text `现在可以任意读写了😀
