### ISSUE TITLE
支持“输入错误时所有输入框都变色”

### ISSUE THREAD

**Issue by ipad4** [zhwayne/WLUnitField#12]
希望可以支持：所有输入框同时变色，以实现输入内容校验失败时的UI变化

**Comment by zhwayne** [comment]
你可以将 trackTintColor 和 tintColor 设置为同一颜色值以实现该需求。

**Comment by zhwayne** [comment]
> 希望可以支持：所有输入框同时变色，以实现输入内容校验失败时的UI变化

你可以将 trackTintColor 和 tintColor 设置为同一颜色值以实现该需求。
