### ISSUE TITLE
调用becomeFirstResponder，光标不在中心位置

### ISSUE THREAD

**Issue by ipad4** [zhwayne/WLUnitField#13]
初始化时，调用becomeFirstResponder，光标不在中心位置，偏向了右侧
![WLUnitField_issue](https://user-images.githubusercontent.com/3615641/57668180-0fb14500-7639-11e9-903d-7b9c9cefc90a.png)

**Comment by zhwayne** [comment]
emm, 注意到了，现在已经修复。
