### ISSUE TITLE
如何修改每个输入格子的背景色

### ISSUE THREAD

**Issue by tasselx** [zhwayne/WLUnitField#14]
现在是没有设置背景色的方法

**Comment by zhwayne** [comment]
你好，暂不支持为每个单元格设置不同背景。

**Comment by tasselx** [comment]
感谢回复，我这边是想设置统一的背景色不要边框 作者有计划加这个么:joy:

**Comment by zhwayne** [comment]
只需要将`backgroundColor`,`tintColor` 设置为同一颜色即可，你可以这么做：

```swift
let color = UIColor.white;
unitFiled.backgroundColor = color
unitFiled.tintColor = color
unitFiled.trackTintColor = color // 如果也不需要跟踪边框颜色
```

**Comment by tasselx** [comment]
你好，您的代码里面setBackgroundColor中设置了透明，我尝试修改会正常的set
```
- (void)setBackgroundColor:(UIColor *)backgroundColor {
_backgroundColor = [UIColor clearColor];
```
```
- (void)setBackgroundColor:(UIColor *)backgroundColor {
_backgroundColor = backgroundColor;
```
backgroudColor,tintColor设置同一颜色的时候
如下效果,是整个块都为同一颜色，还是没有实现单个块的背景色，是我操作问题吗
![image](https://user-images.githubusercontent.com/2656142/59253062-0929e380-8c60-11e9-8fd0-5427689d9e4f.png)

**Comment by zhwayne** [comment]
emmmm，可以理解为这是一个 bug，稍后会修复🙏

**Comment by tasselx** [comment]
:+1: 感谢大佬回复，希望能尽快修复下，大佬项目很棒，准备在项目中使用呢

**Comment by zhwayne** [comment]
已修复，感谢支持。

**Comment by tasselx** [comment]
🙏谢谢大佬，可以了
