### ISSUE TITLE
自动填写验证码问题

### ISSUE THREAD

**Issue by ghost** [zhwayne/WLUnitField#16]
请问点击自动填写后 能否提供API触发回调呢 尝试过valuechange同样无反应 racobserve text也无回调

**Comment by miaozhihui** [comment]
我也遇到这个问题了，我已经解决了，可以联系我，我的微信号m15896657240，上边没法截图

**Comment by jackhanm** [comment]
请问是怎么解决的

**Comment by jackhanm** [comment]
> 我也遇到这个问题了，我已经解决了，可以联系我，我的微信号m15896657240，上边没法截图

请问是怎么解决的

**Comment by zhwayne** [comment]
已做了修改，下载最新版替换原版本，看是否解决了你的问题
