### ISSUE TITLE
iPhone XR 无法设置 inputDelegate

### ISSUE THREAD

**Issue by Zhangguiguang** [zhwayne/WLUnitField#19]
在 XR 手机上，设置inputDelegate可以赋值成功
但是当键盘弹出之后，inputDelegate 会被自动赋值为另一个对象 UIKeyboardImpl
模拟器上就能复现

**Comment by zhwayne** [comment]
你好，请不要手动设置 `inputDelegate` 属性，[官方文档](https://developer.apple.com/documentation/uikit/uitextinput/1614508-inputdelegate)对该属性有简要说明:

> **The text input system automatically assigns a delegate to this property at runtime.**  It is the responsibility of the view that adopts the UITextInput protocol to notify the input delegate at the appropriate junctures.

**Comment by Zhangguiguang** [comment]
很棒！我明白了。
我用 `inputDelegate` 的本意是为了监听输入框的文本内容。
因为之前我监听 `UIControlEventValueChanged` 或者 `KVO text` 都有点小问题
我再仔细看了你的代码，似乎我应该监听 `UIControlEventEditingChanged` 是吧？
老哥的工具写的真棒！谢谢了
