### ISSUE TITLE
unitSpace大于0时无法修改tincolor

### ISSUE THREAD

**Issue by chanbendong** [zhwayne/WLUnitField#4]

**Comment by zhwayne** [comment]
@chanbendong 能否提供具体 Demo 或者操作流程？

**Comment by chanbendong** [comment]
在_drawBoreder:unitSize:方法里面，当_unitSpace>=2的时候，如果输入的字符等于unitCount则无法刷新borderColor

**Comment by zhwayne** [comment]
@chanbendong 明白了。这是一个 feature，当 `unitSpace` ≤ 1 （处于连续模式下），`unitField` 会忽略跟踪色（trackTintColor）。在 `unitSpace` ≥ 2 且当已输入的字符数量等于 `unitCount` 时，trackTintColor 会完全覆盖 `tintColor`， 因此表现为 `tintColor ` 无效。相关信息可查看源码注释😀。

**Comment by chanbendong** [comment]
好的，谢谢大佬
