### ISSUE TITLE
是否不支持数字以外的字符？

### ISSUE THREAD

**Issue by ajunjunandtmac** [zhwayne/WLUnitField#7]
我在.m文件中的@synthesize成员全部注释掉，然后实现UITextInputTraits协议。目前测试看好像可以支持其他字符了。 请问会有什么风险吗？

**Comment by zhwayne** [comment]
@ajunjunandtmac  UnitField 目前只是简单的实现了 `UIKeyInput ` 协议，因此存在的问题是使用系统输入法时，无法顺畅地输入非 ascii 字符。假如您已经**正确实现**了 `UITextInputTraits` 协议，需要注意 `text` 属性的设置及对应的文本绘制，它由一个数组组合而来。如果可以，能否贡献您的代码？😅

**Comment by ajunjunandtmac** [comment]
@zhwayne 可以的，我只做了一点点改动，我再测试一下吧。

**Comment by Laughing1206** [comment]
WLUnitField需要把键盘取消联想，在iPhone8的手机上，键盘的第一排会和联想的重叠，导致第一排没法输入

**Comment by zhwayne** [comment]
现在 unitfield 可以支持任意字符了 :)
