### ISSUE TITLE
如何支持iOS12的短信验证码自动填写

### ISSUE THREAD

**Issue by liubang0909** [zhwayne/WLUnitField#9]
如果里面没有uitextfield的话  该怎么才能支持iOS12的短信验证码自动填写

**Comment by wgy6055** [comment]
支持 iOS 12 Autofill 需要实现 UITextInput，可以试一下这个 https://github.com/wgy6055/WGDigitField ，支持 Autofill（5毛一条 😝

**Comment by liubang0909** [comment]
> 支持 iOS 12 Autofill 需要实现 UITextInput，可以试一下这个 https://github.com/wgy6055/WGDigitField ，支持 Autofill（5毛一条 😝
谢谢🙏。已经star 再次感谢

**Comment by LuXiong** [comment]
只需要把UIKeyInput替换为UITextInput即可，源码已经实现所有的require方法

**Comment by zhwayne** [comment]
@LuXiong @liubang0909  替换为 `UITextInput` 并不能实现 Autofill，还需要实现 `-setMarkedText:selectedRange:` 及 `-unmarkText` 方法。

`WLUnitField` 目前已完美支持 Autofill，感谢关注😜
